version: "3.8"
services:
  web:
    build: .
    command: gunicorn parsing_logs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  test_postgres:
    image: postgres
    restart: always
    ports:
      - "15433:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test_parsing_logs
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass pass
  celery:
    build: .
    command: celery -A parsing_logs worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
