version: "3.8"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/parsing_logs"
      CELERY_BROKER_URL: "redis://:pass@redis:6379/0"
  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: parsing_logs

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass pass
