# Generated by Django 3.1.5 on 2021-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLogORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('uri', models.TextField()),
                ('status_code', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
