# Generated by Django 3.1.5 on 2021-01-18 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatusORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('start', 'Start'), ('finish', 'Finish')], default='start', max_length=8)),
            ],
        ),
    ]
